name: Makefile CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'

    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    - run: nvcc -V
    
    - name: Install sdsl-lite dependencies
      run: |
        cd ..
        git clone https://github.com/vgteam/sdsl-lite.git
        cd sdsl-lite
        ./install.sh
    - name: Compile gbwt-parallel project
      run: |
        cd ${{ github.workspace }}
        make -j 8
    - name: Run unit tests
      run: |
        cd ${{ github.workspace }}/unittest
        make
        ./test_build
